version: "3"

services:
    api:
        container_name: recipe-api
        build:
            context: .
        image: recipe-api
        restart: unless-stopped
        environment:
            - PORT=3000
            - SQLITE_PATH=/db.sqlite
        volumes:
            - ./logs:/logs
            - ./db.sqlite:/db.sqlite
        networks:
            - recipe-network
        ports:
            - "8888:3000"

networks:
    recipe-network:
        driver: bridge
